version: '3.9'

services:
  proxy-frontend:
    build: ./proxy-frontend
    container_name: nanogpt-proxy-frontend
    restart: unless-stopped
    depends_on:
      - proxy
    ports:
      - "8080:8080"
    volumes:
      - ./proxy-frontend

  proxy:
    build: ./proxy
    container_name: nanogpt-proxy
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./proxy/keys.db:/app/keys.db
    environment:
      - DB_ENCRYPTION_KEY=${DB_ENCRYPTION_KEY}
    depends_on:
      - db

  db:
    image: nouchka/sqlite3    
    container_name: nanogpt-proxy-db
    restart: unless-stopped
    command: tail -f /dev/null
    volumes:
      - ./proxy/keys.db:/data/keys.db
